travis:
  secure:
    BINSTAR_TOKEN: crjk/1zmvP8/3TdCvavwhECbeRft1rCfWc4wgIkqoOGJ93f+K6lnK8B8nnbmFa+STwpunYNE9Zj0ZqScOJkFxl1RcC9yayixDODk7QqnGMlvY/W4+Q4WDr9B+eWC4tUPXYmSbQ5jeGtr3OaHLLj2KrfEoyctyI3cWHNEkTeA7/ZwjY0qaWUzTSLlCf9tpB+EvNC4uOgFE/25p0Zn7JE6VgI+LikZGJe9BFSL6fu4LN8LAK6bXr1HUt8z3/CGlR4k+h46IcqRy/9vqRF9XriDiWusoeT2QMU9/hWbPK0LFIAjuxuPvAnXsUtSLk6lwgTQaNc5j4paPHUPTUIwoUBoJ54CSJFebO3E8GahgF/Z7e152pOlD6utZyMNWiiusEl5fSaCWd1k5MQKByg8rsIDXAEfPBv/VT7ScvFh77le27HDylbCDErWE2yr0tme/4jUaKZCE5ilzrXBjGQCUCDWSA+BSQ8UXFxyYTbz35rbj/059RBT8IHxwJDQs7tRNwpFslbD/x+i2p8mNpzPTPZZU3VvVgWFujCTez4YbbtWZwhgZFH77wChrIkpRVgpMs87YyqEoNBwMRXfcH0yjyGaNJzRovwkCsvWWr80cLJOKXBp2rTXWIwsU06cRBwLG5e/1w0RIk6qR3hRPbFkpDBllweACvabYIeE4MvsIqGeliU=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
